_target_: ???
# the choice of beta schedule has big impact on performance
# we found squared cosine works the best
beta_schedule: squaredcos_cap_v2
# clip output to [-1,1] to improve stability
clip_sample: True
# our network predicts noise (instead of denoised action)
prediction_type: 'epsilon'
