_target_: scalingup.algo.diffusion_utils.DiscreteDiffusionEncoderDecoder
action_dim: ???
decoder_horizon: ???
encoder_horizon: ???
cond_dim: ???
n_encoder_layer: ???
n_decoder_layer: ???
n_head: ???
n_emb: ???
p_drop_emb: ???
p_drop_attn: ???
diff_step_cond: ???
pos_emb_type: ???
diffusion_step_embed_dim: ???
