_target_: scalingup.algo.diffusion.DiffusionPolicy.from_path_not_use_EMA
inference_device: 'cuda'
path: ???
remote: True
task_metric_guidance: null
suppress_token: null
towards_token: null
num_inference_steps: null
action_horizon: null
