defaults:
  - replay_buffer: RL_image
  - override state_sequence_encoder/vision_encoder@state_sequence_encoder1.vision_encoder: image_robomimic # {image_robomimic, image_resnet}
  - override state_sequence_encoder/vision_encoder@state_sequence_encoder2.vision_encoder: image_robomimic # {image_robomimic, image_resnet}
  - _self_
replay_buffer:
  obs_dim: ${..state_sequence_encoder1.vision_encoder.obs_dim}
