action_dim: 13
replay_buffer:
  control_representation: ee
  rotation_representation: mat
ctrl_config:
  control_type: 1 # scalingup.utils.core.ControlType.END_EFFECTOR
  rotation_type: 1 # scalingup.utils.core.RotationType.ROT_MAT
  dof: 13
