defaults:
  - point_cloud
  -  ../../../discretizer@discretizer: default
  - _self_


_target_: scalingup.algo.state_encoder.conv3d_encoder.Conv3DVolumeEncoder
output_dim: 512
flattened_dim: 1024
f_maps:
 - 4
 - 8
 - 16
 - 32
 - 64
 - 128
